### ISSUE TITLE
Checking multiple source files fails

### ISSUE THREAD

**Issue by skrobinson** [JacobDomagala/StaticAnalysis#33]
I think there is an issue in `entrypoint.sh` with `files_to_check`, affecting `debug_print` and `eval clang-tidy-12...`.

The problem shows up when trying to run `clang-tidy` over mutliple files and seems to be related to how `get_files_to_check.py` output is split when setting `files_to_check`. Everything works as expected for a single source file.

I have created a [minimal failing case](https://github.com/skrobinson/TestRepo/pull/1). Let me know if I can add any more information.

**Comment by JacobDomagala** [comment]
Thanks for catching that! I haven't been using this Action lately after the recent changes. I should probably create some testing suite for catching this type of bugs in future.
