### ISSUE TITLE
How to custom the docker container?

### ISSUE THREAD

**Issue by zkyd** [JacobDomagala/StaticAnalysis#42]
I want to use it in the Archlinux system, how do it?

**Comment by skrobinson** [comment]
The only way I know to use a custom Docker image is to fork StaticAnalysis (SA) and make changes to `Dockerfile`.  Look in `docker/static_analysis.dockerfile` for a list of additional software SA needs installed in the Docker image.

Version differences between Ubuntu/Debian packages and Archlinux packages may cause SA to not work in the new image.

Good luck and let us know how Archlinux works out.

**Comment by JacobDomagala** [comment]
For now it runs only on Ubuntu (https://github.com/JacobDomagala/StaticAnalysis/blob/master/docker/static_analysis.dockerfile). 

If having multiple docker files is something people would want, we could potentially have some kind of user input to specify which docker file should be used.

**Comment by JacobDomagala** [comment]
So I'm closing this issue for now
