### ISSUE TITLE
Support for makefile based projects

### ISSUE THREAD

**Issue by akshaim** [JacobDomagala/StaticAnalysis#70]
My current project does not use CMake to build a makefile. Instead, we write the makefile since it's pretty complex. Is there a possibility of using make projects directly ?

I can execute `cppcheck` and `clang-tidy` to generate  `XML` outputs.  Can you add an option to parse the `XML` ?

**Comment by JacobDomagala** [comment]
I've added input option `use_cmake` which disables CMake. Then globing function is used to collect all files (together with `exclude_dirs`). 
Let me know if it works for you.
