### ISSUE TITLE
custom build directory

### ISSUE THREAD

**Issue by jbbjarnason** [JacobDomagala/StaticAnalysis#91]
Is it possible to specify custom build directory?

This would be super useful when `binaryDir` tag is set in CMakePresets (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html)

**Comment by JacobDomagala** [comment]
Currently it's not possible (SA will create 'build' directory "$GITHUB_WORKSPACE/build"). I agree that it could be useful, I will try to add it soon. Thanks!

**Comment by JacobDomagala** [comment]
After reading a bit about the presets, wouldn't setting the `cmake_args` action input with "--preset xxx" or `-b xxx` as another way of specifying output dir be sufficent? 

Is that something that you had in mind?

**Comment by jbbjarnason** [comment]
I did not work to pass `-B build --preset <preset_name>` I got weird errors so I made a new preset with `build` as build directory which works fine

**Comment by JacobDomagala** [comment]
Closing the issue then
